# Generated by Django 4.1.3 on 2022-11-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debited_account_id', models.IntegerField()),
                ('credited_account_id', models.IntegerField()),
                ('value', models.IntegerField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Status',
            new_name='Accounts',
        ),
        migrations.DeleteModel(
            name='MoneyTransfer',
        ),
    ]
